[Doc] Add the model description in rtmdet_description.md
open-mmlab/mmyolo pull request #103
Opened 2022-09-28 10:23 UTC by RangeKing

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Add the model description of RTMDet.

## Modification

rtmdet_description.md

2022-09-28 10:43 UTC, satuoqaq commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +同时，RTMDet 也延续了作者之前在 [NanoDet](https://zhuanlan.zhihu.com/p/306530300) 中的思想，使用 [Quality Focal Loss](https://arxiv.org/abs/2011.12885)，去掉 Objectness 分支并去掉 Objectness 分支，进一步将 Head 轻量化。
```suggestion
同时，RTMDet 也延续了作者之前在 [NanoDet](https://zhuanlan.zhihu.com/p/306530300) 中的思想，使用 [Quality Focal Loss](https://arxiv.org/abs/2011.12885)，并去掉 Objectness 分支，进一步将 Head 轻量化。
```

2022-09-28 12:06 UTC, PeterH0323 requested changes

2022-09-28 12:06 UTC, PeterH0323 commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +在集成了如此多高性能高精度的学术界以及工业界的模型之后，RTMDet也对这些它们的结构
```suggestion
在集成了如此多高性能高精度的学术界以及工业界的模型之后，RTMDet 也对这些它们的结构
```

2022-09-28 12:06 UTC, PeterH0323 commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +设计以及训练方式进行了经验性的总结，并进行了优化，推出了 RTMDe t高精度、低延时的
```suggestion
设计以及训练方式进行了经验性的总结，并进行了优化，推出了 RTMDet 高精度、低延时的
```

2022-09-28 12:06 UTC, PeterH0323 commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +由于 ` CSPNeXt Block` 内使用了 `depth-wise` 卷积，单个 block 内的层数增多，如果保持原有的 stage 内的 block 数，则会导致模型的推理速度大幅降低。
```suggestion
由于 `CSPNeXt Block` 内使用了 `depth-wise` 卷积，单个 block 内的层数增多，如果保持原有的 stage 内的 block 数，则会导致模型的推理速度大幅降低。
```

2022-09-28 12:42 UTC, hhaAndroid commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +在集成了如此多高性能高精度的学术界以及工业界的模型之后，RTMDet也对这些它们的结构
```suggestion
在调研了当前 YOLO 系列的诸多改进模型后，MMDetection 核心开发者针对这些设计...
```

2022-09-28 12:42 UTC, hhaAndroid commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +其中，RTMDet-x 在 52.6 mAP 的精度下达到了300+FPS的推理速度。
中英文之间要空格

2022-09-28 12:42 UTC, hhaAndroid commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +其中，RTMDet-x 在 52.6 mAP 的精度下达到了300+FPS的推理速度。
300FPS 要用括号说明是啥平台，以及是否包括后处理，不能给人以不严谨的看法

2022-09-28 12:42 UTC, hhaAndroid commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +而最轻量的模型 RTMDet-tiny，在仅有4M参数量的情况下也能够达到 40.9 mAP，且推理速度 \<1ms。
推理时间都注明平台

2022-09-28 12:42 UTC, hhaAndroid commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +**注**：推理速度测试（不包含 NMS）是在 1 块 NVIDIA 3090 GPU 上的 `TensorRT 8.4.3, cuDNN 8.2.0, FP16, batch size=1` 条件里测试的。
直接放到 300+ 那个地方下一段，不要隔那么远

2022-09-28 12:42 UTC, hhaAndroid commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +RTMDet 模型整体结构与目前主流的检测器 YOLO 系列相似。以 **L**arge 模型为例，整体由 `CSPNeXt` + `CSPNeXtPAFPN` + `共享卷积权重但分别计算 BN 的 Head` 构成。
```suggestion
RTMDet 模型整体结构与目前主流的检测器 YOLO 系列相似。以 **L**arge 模型为例，整体由 `CSPNeXt` + `CSPNeXtPAFPN` + `共享卷积权重但分别计算 BN 的 SepBNHead` 构成。
```

2022-09-28 12:42 UTC, hhaAndroid commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +### Neck
可以简要介绍，说明其结构和 YOLOX 几乎一致，内部核心模块也是 CSPLayer，只不过引入了 cspnext_block

2022-09-28 12:42 UTC, hhaAndroid commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +**注**：MMYOLO 和 MMDetection 中 Neck 的具体实现和连接有细微不同。
实现不同，但是连接相同把，不相同那精度也对不上把

2022-09-28 12:42 UTC, hhaAndroid commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +RTMDet 参考了 NAS-FPN 中的做法，使用了 `SepBNHead`，在不同层之间共享卷积权重，但是独立计算 BN 的统计量。
NSA-FPN 给一下论文链接

2022-09-28 13:47 UTC, hhaAndroid commented on docs/zh_cn/algorithm_descriptions/rtmdet_description.md
> +所以 RTMDet 选择不引入额外的连接，而是改变 Backbone 与 Neck 间参数量的配比。
要说明是通过手动调整 backbone 和 neck 的 expand_ratio 参数来调整配比

2022-09-29 04:32 UTC, hhaAndroid approved these changes

2022-09-29 04:33 UTC, merged