[Draft] Translate yolov5_tutorial.md
open-mmlab/mmyolo pull request #138
Opened 2022-10-09 02:40 UTC by xin-li-67

## Motivation

Translate yolov5 tutorial.

## Modification

 - docs/en/user_guides/yolov5_tutorial.md

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDetection or MMClassification.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2022-10-09 02:44 UTC, PeterH0323 requested changes

2022-10-09 02:44 UTC, PeterH0323 commented on docs/en/user_guides/yolov5_tutorial.md
> +python tools/dataset_converters/balloon2coco.py
```suggestion
python tools/misc/download_dataset.py  --dataset-name balloon \
                                                                  --save-dir data \
                                                                  --unzip
python tools/dataset_converters/balloon2coco.py
```

2022-10-09 02:44 UTC, PeterH0323 commented on docs/en/user_guides/yolov5_tutorial.md
> +After executing the above command, the balloon dataset will be downloaded in the `data` folder with the converted format we need. The `train.json` and `val.json` are the annotation files; both are in
```suggestion
After executing the above command, the balloon dataset will be downloaded in the `data` folder with the converted format we need. The `train.json` and `val.json` are the annotation files, both are in the coco format.
```

2022-10-09 10:18 UTC, PeterH0323 requested changes

2022-10-09 10:18 UTC, PeterH0323 commented on docs/en/user_guides/yolov5_tutorial.md
> +```shell
```suggestion
```python
```

2022-10-09 11:16 UTC, hhaAndroid commented on docs/en/user_guides/yolov5_tutorial.md
> +# YOLOv5: From Start to Deploy
From getting started to deployment with YOLOv5

2022-10-09 11:16 UTC, hhaAndroid commented on docs/en/user_guides/yolov5_tutorial.md
> +python tools/misc/download_dataset.py  --dataset-name balloon \
python tools/misc/download_dataset.py  --dataset-name balloon --save-dir data --unzip

2022-10-09 15:18 UTC, cydiachen commented on docs/en/user_guides/yolov5_tutorial.md
> +Run the above command, the inference result picture will be automatically saved to the `work_dirs/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon/{timestamp}/show_results` folder. The following is one of
The left and the right

2022-10-09 15:26 UTC, cydiachen commented on docs/en/user_guides/yolov5_tutorial.md
> +In this tutorial, the training dataset for MMYOLO is less than 40MB and is selected from the balloon dataset.
In this tutorial, we provide the ballon dataset, which is less than 40MB, as the training dataset for MMYOLO.

2022-10-09 15:27 UTC, cydiachen commented on docs/en/user_guides/yolov5_tutorial.md
> +After executing the above command, the balloon dataset will be downloaded in the `data` folder with the converted format we need. The `train.json` and `val.json` are the annotation files, both are in
The `train.json` and `val.json` are the annotation files in the coco format.

2022-10-09 15:29 UTC, cydiachen commented on docs/en/user_guides/yolov5_tutorial.md
> +We set the `interval` of the logger to 1 because each iteration of the `interval` will output a loss-related log, and the balloon dataset we use is relatively tiny. We will not see the loss-related o
```suggestion
The reason why we set the `interval` of the logger to 1 is that the balloon data set we choose is relatively small, and if the `interval` is too large, we will not see the output of the loss-related log. Therefore, by setting the `interval` of the logger to 1 will ensure that each interval iteration will output a loss-related log.
```
You can decide by your own.

2022-10-09 15:30 UTC, cydiachen commented on docs/en/user_guides/yolov5_tutorial.md
> +Our testing shows that with the YOLOv5-s pretrained model to train and validate, the coco/bbox_mAP can increase by more than 30 percent on the balloon dataset compared with not using the pre-training
NOTICE: It is highly recommended that finetuning from large datasets, such as COCO, can significantly boost the performance of overall network. 
In this example, compared with training from scratch, finetuning the pretrained model outperforms with a significant margin. (Over 30+ mAP boost than training from scratch).

2022-10-09 15:31 UTC, cydiachen commented on docs/en/user_guides/yolov5_tutorial.md
> +Then re-run the following training command. During the validation, each `interval` image will save a puzzle of the annotation and prediction results to `work_dirs/yolov5_s-v61_syncbn_fast_1xb4-300e_b
Re-run

2022-10-10 00:56 UTC, xin-li-67 commented
@hhaAndroid @cydiachen Thanks for the corrections. Please take a look at my latest version~

2022-10-10 02:41 UTC, hhaAndroid approved these changes

2022-10-10 02:42 UTC, merged