Ppyoloe
open-mmlab/mmyolo pull request #145
Opened 2022-10-10 07:16 UTC by Nioolek

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

add ppyoloe and ppyoloeplus

## Modification

Please briefly describe what modification is made in this PR.

2022-10-10 07:23 UTC, hhaAndroid commented
@Nioolek Please fix the conflicting files

2022-10-13 10:13 UTC, PeterH0323 requested changes

2022-10-14 14:47 UTC, PeterH0323 requested changes

2022-10-14 14:47 UTC, PeterH0323 commented on configs/ppyoloe/ppyoloe_plus_m_fast_8xb8-80e_coco.py
> +    bbox_head=dict(head_module=dict(widen_factor=widen_factor), ))
```suggestion
    bbox_head=dict(head_module=dict(widen_factor=widen_factor)))
```

2022-10-14 14:47 UTC, PeterH0323 commented on configs/ppyoloe/ppyoloe_plus_x_fast_8xb8-80e_coco.py
> +    bbox_head=dict(head_module=dict(widen_factor=widen_factor), ))
```suggestion
    bbox_head=dict(head_module=dict(widen_factor=widen_factor)))
```

2022-10-14 14:47 UTC, PeterH0323 commented on mmyolo/models/backbones/csp_resnet.py
> +        return stage
这里可否直接写成
```python
return [cspres_layer]
```

2022-10-14 14:47 UTC, PeterH0323 commented on mmyolo/models/dense_heads/ppyoloe_head.py
> +    def forward(self, feat, avg_feat):
type hint

2022-10-14 14:47 UTC, PeterH0323 commented on mmyolo/models/backbones/csp_resnet.py
> +    def forward(self, x):
type hint

2022-10-14 14:47 UTC, PeterH0323 commented on mmyolo/models/backbones/csp_resnet.py
> +    def forward(self, x):
type hint

2022-10-14 14:47 UTC, PeterH0323 commented on mmyolo/models/layers/yolo_bricks.py
> +    def forward(self, x):
type hint

2022-10-14 14:47 UTC, PeterH0323 commented on mmyolo/models/necks/ppyoloe_customcsppan.py
> +    def forward(self, x):
type hint

2022-10-18 02:58 UTC, hhaAndroid commented on mmyolo/datasets/ppyoloe_coco.py
> +class PPYOLOECocoDataset(CocoDataset):
unnecessary

2022-10-18 02:58 UTC, hhaAndroid commented on configs/ppyoloe/ppyoloe_plus_s_fast_8xb8-80e_coco.py
> +        type='PPYOLOECustomCSPPAN',
PPYOLOECustomCSPPAN ->PPYOLOECSPPAN

2022-10-21 11:39 UTC, hhaAndroid commented on configs/ppyoloe/ppyoloe_plus_l_fast_8xb8-80e_coco.py
> +_base_ = './ppyoloe_plus_s_syncbn_fast_8xb32-300e_coco.py'
```suggestion
_base_ = './ppyoloe_plus_s_fast_8xb32-300e_coco.py'
```

2022-10-21 11:39 UTC, hhaAndroid commented on configs/ppyoloe/ppyoloe_plus_l_fast_8xb8-80e_coco.py
> +_base_ = './ppyoloe_plus_s_syncbn_fast_8xb32-300e_coco.py'
Let's put all the configurations of the non-plus version, but we will not to train.

2022-10-21 11:39 UTC, hhaAndroid commented on configs/ppyoloe/ppyoloe_plus_l_fast_8xb8-80e_coco.py
> +    bbox_head=dict(head_module=dict(widen_factor=widen_factor), ))
```suggestion
    bbox_head=dict(head_module=dict(widen_factor=widen_factor)))
```

2022-10-21 11:39 UTC, hhaAndroid commented on configs/ppyoloe/ppyoloe_plus_l_fast_8xb8-80e_coco.py
> +train_batch_size_per_gpu = 8
train_batch_size_per_gpu invalid

2022-10-21 11:39 UTC, hhaAndroid commented on configs/ppyoloe/ppyoloe_plus_m_fast_8xb8-80e_coco.py
> +_base_ = './ppyoloe_plus_s_syncbn_fast_8xb32-300e_coco.py'
```suggestion
_base_ = './ppyoloe_plus_s_fast_8xb32-300e_coco.py'
```

2022-10-21 11:39 UTC, hhaAndroid commented on configs/ppyoloe/ppyoloe_plus_s_fast_8xb8-80e_coco.py
> +dataset_type = 'mmdet.CocoDataset'
YOLOv5COCOxxx

2022-10-21 11:39 UTC, hhaAndroid commented on configs/ppyoloe/ppyoloe_plus_s_fast_8xb8-80e_coco.py
> +env_cfg = dict(cudnn_benchmark=True)
delete

2022-10-21 11:39 UTC, hhaAndroid commented on configs/ppyoloe/ppyoloe_plus_s_fast_8xb8-80e_coco.py
> +    data_preprocessor=dict(
The fast version is not written in this way

2022-10-21 11:39 UTC, hhaAndroid commented on configs/ppyoloe/ppyoloe_plus_s_fast_8xb8-80e_coco.py
> +        act_cfg=dict(type='Swish'),
```suggestion
        act_cfg=dict(type='nn.SiLu'),
```

2022-10-21 11:39 UTC, hhaAndroid commented on mmyolo/models/backbones/csp_resnet.py
> +    """PPYOLOE Backbone Stage."""
docstr too little information

2022-10-21 11:39 UTC, hhaAndroid commented on mmyolo/models/backbones/csp_resnet.py
> +        self.conv1 = ConvModule(
If there is a specific meaning, it is best not to use 123 instead

2022-10-21 11:39 UTC, hhaAndroid commented on mmyolo/models/backbones/csp_resnet.py
> +        if use_attn:
use_effective_se

2022-10-21 11:39 UTC, hhaAndroid commented on mmyolo/models/backbones/csp_resnet.py
> +               [256, 512, 6, True, False], [512, 1024, 3, True, False]]
Can the user set use_spp=True? Don't expose parameters if not allowed

2022-10-21 11:39 UTC, hhaAndroid commented on mmyolo/models/backbones/csp_resnet.py
> +                    make_divisible(self.arch_setting[0][0], self.widen_factor)
int() replace

2022-10-21 11:39 UTC, hhaAndroid commented on mmyolo/models/necks/yolov5_pafpn.py
> +                 out_channels: List[int],
```suggestion
                 out_channels: Union[List[int],int],
```

2022-10-21 11:39 UTC, hhaAndroid commented on mmyolo/models/necks/ppyoloe_csppan.py
> +class SPP(nn.Module):
why not put it to the backbone?

2022-10-22 03:05 UTC, Nioolek commented on mmyolo/models/necks/ppyoloe_csppan.py
> +class SPP(nn.Module):
PPYOLOE only use `spp` in neck

2022-10-27 06:39 UTC, hhaAndroid commented on configs/ppyoloe/ppyoloe_plus_s_fast_8xb8-80e_coco.py
> +    dict(type='LoadAnnotations', with_bbox=True),
dict(type='LoadAnnotations', with_bbox=True, _scope_='mmdet'),

2022-10-27 06:39 UTC, hhaAndroid commented on mmyolo/models/backbones/csp_resnet.py
> +        block_cfg['norm_cfg'] = norm_cfg
block_cfg.setdefault('out_channels, norm_cfg)
block_cfg.setdefault('act_cfg, act_cfg)

2022-10-27 06:39 UTC, hhaAndroid commented on mmyolo/models/backbones/csp_resnet.py
> +            self.attn = EffectiveSELayer(
也改成可注册模式？

2022-10-27 06:39 UTC, hhaAndroid commented on mmyolo/models/backbones/csp_resnet.py
> +            self.attn = EffectiveSELayer(
这样就不需要 use_efff_se 这个参数了

2022-10-27 06:39 UTC, hhaAndroid commented on mmyolo/models/backbones/csp_resnet.py
> +class CSPResStage(nn.Module):
如果可以和 neck 的 CSPStage 合并，我建议放到 layer 文件里面去

2022-10-27 06:39 UTC, hhaAndroid commented on mmyolo/models/necks/ppyoloe_csppan.py
> +    def build_convs_layer(self, block_cfg: ConfigType, middle_channels: int,
```suggestion
    def build_block_layer(self, block_cfg: ConfigType, middle_channels: int,
```

2022-10-27 06:39 UTC, hhaAndroid commented on mmyolo/models/necks/ppyoloe_csppan.py
> +        self.convs = self.build_convs_layer(block_cfg, middle_channels,
self.blocks

2022-10-27 06:39 UTC, hhaAndroid commented on mmyolo/models/necks/ppyoloe_csppan.py
> +                 out_channels: Union[int, List[int]] = [256, 512, 1024],
如果你类不支持单独一个 Int，那就不要写 union

2022-10-27 06:39 UTC, hhaAndroid commented on mmyolo/models/necks/ppyoloe_csppan.py
> +                 use_drop_block: bool = False,
不需要两个参数，drop_block_cfg 支持 none 参数jike

2022-10-27 06:39 UTC, hhaAndroid commented on mmyolo/models/necks/ppyoloe_csppan.py
> +            channels = [self.in_channels[idx]
这个很奇怪

2022-10-27 06:48 UTC, hhaAndroid commented on mmyolo/models/necks/ppyoloe_csppan.py
> +                 num_stage: int = 1,
num_csplayer

2022-10-27 06:48 UTC, hhaAndroid commented on mmyolo/models/backbones/csp_resnet.py
> +class CSPResStage(nn.Module):
CSPResStage -> CSPResLayer

2022-10-27 06:48 UTC, hhaAndroid commented on mmyolo/models/necks/ppyoloe_csppan.py
> +class PPYOLOECSPPAN(BaseYOLONeck):
```suggestion
class PPYOLOECSPPAFPN(BaseYOLONeck):
```

2022-10-27 06:48 UTC, hhaAndroid commented on mmyolo/models/necks/ppyoloe_csppan.py
> +                 block_cfg: ConfigType = dict(
num_block 参数放到 blck_cfg前面，放一起，比较好理解

2022-10-27 12:08 UTC, hhaAndroid commented on mmyolo/models/backbones/csp_resnet.py
> +                 effective_se_cfg: ConfigType = dict(
attention_cfg

2022-10-27 12:08 UTC, hhaAndroid commented on mmyolo/models/dense_heads/ppyoloe_head.py
> +            conv.bias = nn.Parameter(b.view(-1), requires_grad=True)
openmmlab 不支持这种写法好像，你可以看下yolov5 写法

2022-10-27 12:08 UTC, hhaAndroid commented on mmyolo/models/dense_heads/ppyoloe_head.py
> +        for in_c in self.in_channels:
in_c -> in_channel

2022-10-27 12:08 UTC, hhaAndroid commented on mmyolo/models/dense_heads/ppyoloe_head.py
> +        for in_c in self.in_channels:
in_c -> in_channel

2022-10-27 12:08 UTC, hhaAndroid commented on mmyolo/models/layers/yolo_bricks.py
> +class ESEAttn(nn.Module):
ESEAttn 和 EffectiveSELayer 好奇怪呀？ 两者就差了一个 atten?

2022-10-27 12:08 UTC, hhaAndroid commented on mmyolo/models/layers/yolo_bricks.py
> +class SPP(nn.Module):
PPOYLOESPPFBottleneck。 我们直接支持 fast 版本

2022-10-27 12:08 UTC, hhaAndroid commented on mmyolo/models/layers/yolo_bricks.py
> +class SPP(nn.Module):
这个可以直接复用我们已经实现的 SPPFBottleneck 吗

2022-10-27 12:08 UTC, hhaAndroid commented on mmyolo/models/layers/yolo_bricks.py
> +                 effective_se_cfg: OptMultiConfig = dict(
attention_cfg

2022-10-28 01:41 UTC, hhaAndroid approved these changes

2022-10-28 01:44 UTC, merged