[Feature] Support YOLOv7 inference
open-mmlab/mmyolo pull request #149
Opened 2022-10-11 09:45 UTC by hhaAndroid

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDetection or MMClassification.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2022-10-13 09:15 UTC, PeterH0323 requested changes

2022-10-13 09:15 UTC, PeterH0323 commented on mmyolo/models/layers/yolo_bricks.py
> +    def forward(self, x):
```suggestion
    def forward(self, x) -> Tensor:
```

2022-10-14 07:43 UTC, RangiLyu commented on mmyolo/models/layers/yolo_bricks.py
> +        bottom_out = self.bottom_branches(x)
What is the meaning of top&bottom?

2022-10-14 07:43 UTC, RangiLyu commented on mmyolo/models/layers/yolo_bricks.py
> +class MaxPoolBlock(BaseModule):
May find a better name because this block has not only maxpool but also conv layers

2022-10-14 07:43 UTC, RangiLyu commented on configs/yolov7/yolov7_l_fast_8x16b-300_coco.py
> +    proposal_nums=(100, 1, 10),
add some comments

2022-10-14 14:29 UTC, PeterH0323 approved these changes
LGTM

2022-10-16 06:07 UTC, merged