Update EN version of Yolov5_tutorials
open-mmlab/mmyolo pull request #59
Opened 2022-09-21 09:37 UTC by cydiachen

Update EN version of Yolov5_tutorials and align the environment settings with CN version.

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Update EN version of Yolov5_tutorials

## BC-breaking (Optional)

Update EN version of Yolov5_tutorials

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDetection or MMClassification.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2022-09-22 02:51 UTC, hhaAndroid commented
@cydiachen Please update

2022-09-22 03:59 UTC, PeterH0323 requested changes

2022-09-22 03:59 UTC, PeterH0323 commented on docs/en/user_guides/yolov5_tutorial.md
> +python tools/misc/download_dataset.py  --dataset-name balloon --save-dir data --unzip
```suggestion
python tools/misc/download_dataset.py --dataset-name balloon --save-dir data --unzip
```

2022-09-22 03:59 UTC, PeterH0323 commented on docs/en/user_guides/yolov5_tutorial.md
> +After executing the above command, the command automatically downloads the dataset, converts the format of annotations. The balloon dataset is ready in the `data` folder. The `train.json` and `val.js
```suggestion
After executing the above command, the command automatically downloads the dataset, converts the format of annotations. The balloon dataset is ready in the `data` folder. The `train.json` and `val.json` are the annotation files in COCO format. 
```

2022-09-22 03:59 UTC, PeterH0323 commented on docs/en/user_guides/yolov5_tutorial.md
> +#### Visualization with wandb backend
```suggestion
#### Visualization backend

MMEngine supports various backends such as local, TensorBoard and wandb.

##### Visualization with wandb backend
```

2022-09-22 03:59 UTC, PeterH0323 commented on docs/en/user_guides/yolov5_tutorial.md
> +
```suggestion

##### Visualization with tensorboard backend

Install tensorboard

\```shell
pip install tensorboard
\```

As above, add `tensorboard` configuration in configuration file `configs/yolov5/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon.py`:

\```python
visualizer = dict(vis_backends=[dict(type='LocalVisBackend'),dict(type='TensorboardVisBackend')])
\```

Re-run the training command and tensorboard files will be generated in the visualization folder  `work_dirs/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon/{timestamp}/vis_data`.

Run the following command to see data visualizations of tensorboard such as loss, learning rate and coco/bbox using web browser:

\```shell
tensorboard --logdir=work_dirs/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon
\```

```

2022-09-22 03:59 UTC, PeterH0323 commented on docs/en/user_guides/yolov5_tutorial.md
> +
After you accept this suggestion, pls do remember change " \\\`\`\` " -> " ``` "

2022-09-23 01:46 UTC, PeterH0323 commented
@cydiachen  pls take a look, thx. 😄

2022-09-27 03:27 UTC, closed without merging