[Doc] Add Tensorboard usage method of yolov5_tutorial.md
open-mmlab/mmyolo pull request #66
Opened 2022-09-21 13:38 UTC by satuoqaq

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Add Tensorboard usage method in yolov5_tutorial.md

2022-09-21 15:46 UTC, PeterH0323 requested changes

2022-09-21 15:46 UTC, PeterH0323 commented on docs/zh_cn/user_guides/yolov5_tutorial.md
> +安装Tensorboard环境
安装Tensorboard环境 -> 安装 Tensorboard 环境

2022-09-21 15:46 UTC, PeterH0323 commented on docs/zh_cn/user_guides/yolov5_tutorial.md
> +同上述在配置文件 `configs/yolov5/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon.py`中添加 tensorboard 配置
tensorboard -> `tensorboard`

2022-09-21 15:46 UTC, PeterH0323 commented on docs/zh_cn/user_guides/yolov5_tutorial.md
> +```shell
shell -> python

2022-09-21 15:46 UTC, PeterH0323 commented on docs/zh_cn/user_guides/yolov5_tutorial.md
> +运行命令便可以在命令行中提示的网页链接中看到 loss、学习率和 coco/bbox_mAP 等数据可视化了。
这两行表述需要进行完善

2022-09-21 15:50 UTC, PeterH0323 requested changes

2022-09-21 15:50 UTC, PeterH0323 commented on docs/zh_cn/user_guides/yolov5_tutorial.md
> +tensorboard --logdir = work_dirs/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon
```suggestion
tensorboard --logdir=work_dirs/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon
```

2022-09-21 15:50 UTC, PeterH0323 commented on docs/zh_cn/user_guides/yolov5_tutorial.md
> +```shell
```suggestion
```python
```

2022-09-21 15:50 UTC, PeterH0323 commented on docs/zh_cn/user_guides/yolov5_tutorial.md
> +同上述在配置文件 `configs/yolov5/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon.py`中添加 tensorboard 配置
```suggestion
同上述在配置文件 `configs/yolov5/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon.py`中添加 `tensorboard` 配置
```

2022-09-21 15:50 UTC, PeterH0323 commented on docs/zh_cn/user_guides/yolov5_tutorial.md
> +安装Tensorboard环境
```suggestion
安装 Tensorboard 环境
```

2022-09-22 00:57 UTC, PeterH0323 requested changes

2022-09-22 00:57 UTC, PeterH0323 commented on docs/zh_cn/user_guides/yolov5_tutorial.md
> +##### wandb可视化使用
```suggestion
##### wandb 可视化使用
```

2022-09-22 02:02 UTC, PeterH0323 requested changes

2022-09-22 02:02 UTC, PeterH0323 commented on docs/zh_cn/user_guides/yolov5_tutorial.md
> +运行命令便可以在命令行中提示的网页链接中看到 loss、学习率和 coco/bbox_mAP 等数据可视化了。
```suggestion
运行下面的命令便可以在网页链接使用 Tensorboard 查看 loss、学习率和 coco/bbox_mAP 等可视化数据了：
```

2022-09-22 02:47 UTC, hhaAndroid approved these changes

2022-09-22 02:47 UTC, merged