[Docs]Change the code about installation
open-mmlab/mmyolo pull request #72
Opened 2022-09-23 01:53 UTC by suibe-qingtian

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDetection or MMClassification.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2022-09-23 01:56 UTC, PeterH0323 requested changes

2022-09-23 01:56 UTC, PeterH0323 commented on README_zh-CN.md
>  mim install -e .
```suggestion
# Install MMYOLO
mim install -e .
```

2022-09-23 01:57 UTC, PeterH0323 requested changes

2022-09-23 02:00 UTC, PeterH0323 commented
Hi @suibe-qingtian 
I leave some suggestion for the doc, you can click the `commit suggestion` button if you accept the suggestion change.
Thx for your contribute. 😄

2022-09-23 03:15 UTC, suibe-qingtian commented on README_zh-CN.md
>  mim install -e .
Ok，thanks

2022-09-23 03:15 UTC, suibe-qingtian commented on README_zh-CN.md
> +# for albumentations
ok，thanks

2022-09-23 03:24 UTC, PeterH0323 commented
Hi @suibe-qingtian 

Pls modifiy the English version at the same time: 

- https://github.com/open-mmlab/mmyolo/blob/main/README.md

And I just find out another wrong code in `get_started.md`, pls do the same change for it :
- https://github.com/open-mmlab/mmyolo/blob/main/docs/en/get_started.md
- https://github.com/open-mmlab/mmyolo/blob/main/docs/zh_cn/get_started.md

![image](https://user-images.githubusercontent.com/25873202/191886278-6b99a8ce-2a50-42d8-8287-e88995ce3cbb.png)

2022-09-23 03:45 UTC, PeterH0323 requested changes

2022-09-23 03:45 UTC, PeterH0323 commented on README.md
> +pip install -r requirements/albu.txt
```suggestion
# Install albumentations
pip install -r requirements/albu.txt
# Install MMYOLO
```

2022-09-23 03:45 UTC, PeterH0323 commented on docs/en/get_started.md
> +pip install -r requirements/albu.txt
```suggestion
# Install albumentations
pip install -r requirements/albu.txt
# Install MMYOLO
```

2022-09-23 03:45 UTC, PeterH0323 commented on docs/zh_cn/get_started.md
> +pip install -r requirements/albu.txt
```suggestion
# Install albumentations
pip install -r requirements/albu.txt
# Install MMYOLO
```

2022-09-23 03:50 UTC, PeterH0323 approved these changes
LGTM

2022-09-23 04:30 UTC, RangeKing commented on docs/zh_cn/get_started.md
>  pip install -v -e .
```suggestion
mim install -v -e .
```
To be consistent with `README.md`

2022-09-23 04:30 UTC, RangeKing commented on docs/en/get_started.md
>  pip install -v -e .
```suggestion
mim install -v -e .
```
To be consistent with `README.md`

2022-09-23 04:32 UTC, RangeKing commented on README.md
>  mim install -e .
```suggestion
mim install -v -e .
```

2022-09-23 05:55 UTC, PeterH0323 requested changes

2022-09-23 05:55 UTC, PeterH0323 commented on README_zh-CN.md
>  mim install -e .
```suggestion
mim install -v -e .
```

2022-09-23 07:22 UTC, PeterH0323 commented
Hi @suibe-qingtian 

Pls change merge branch from `main` to `dev`

2022-09-23 09:19 UTC, PeterH0323 approved these changes
LGTM

2022-09-23 11:50 UTC, hhaAndroid approved these changes

2022-09-23 11:50 UTC, merged

2023-04-10 04:53 UTC, OpenMMLab-Assistant005 commented
Hi @qingtian5 ！First of all, we want to express our gratitude for your significant PR in the MMYOLO project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤