[WIP]Add plugin layers for backbone
open-mmlab/mmyolo pull request #75
Opened 2022-09-23 02:53 UTC by wanghonglie

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDetection or MMClassification.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2022-09-23 04:15 UTC, RangeKing reviewed
The example tutorials should be modified accordingly.

2022-09-23 04:15 UTC, RangeKing commented on configs/yolov5/yolov5_s-v61-attn0011-drop0011_syncbn_8xb16-300e_coco.py
> +                    attention_type='0010',
Need to be consistent with the config name.

2022-09-23 04:15 UTC, RangeKing commented on configs/yolov5/yolov5_s-v61-attn0011-drop0011_syncbn_8xb16-300e_coco.py
> +_base_ = '../_base_/default_runtime.py'
It's better to inherit the `_base_ = ./yolov5_s-v61_syncbn_8xb16-300e_coco.py` config?

2022-09-25 13:52 UTC, hhaAndroid commented
@wanghonglie Please add UT

2022-09-26 01:49 UTC, hhaAndroid commented on configs/yolov5/yolov5_s-v61-attn0011-drop_syncbn_8xb16-300e_coco.py
> +_base_ = './yolov5_s-v61_syncbn_8xb16-300e_coco.py'
configs/yolov5/yolov5_s-v61_dropblock-stage0011_syncbn_fast_8xb16-300e_coco.py

2022-09-26 03:16 UTC, hhaAndroid commented on docs/en/advanced_guides/how_to.md
> +            dict(
delete

2022-09-28 00:41 UTC, PeterH0323 requested changes

2022-09-28 00:41 UTC, PeterH0323 commented on docs/en/advanced_guides/how_to.md
> +`cfg`parameter indicates the specific configuration of the plug-in. The `stages` parameter indicates whether to add plug-ins after the corresponding stage of the backbone. The length of list `stages`
```suggestion
`cfg` parameter indicates the specific configuration of the plug-in. The `stages` parameter indicates whether to add plug-ins after the corresponding stage of the backbone. The length of list `stages` must be the same as the number of backbone stages.
```

2022-09-28 00:41 UTC, PeterH0323 commented on docs/zh_cn/advanced_guides/how_to.md
> +MMYOLO支持在BackBone的不同Stage后增加如none_local、dropout等插件，用户可以直接通过修改配置文件中backbone的plugins参数来实现对插件的管理。例如为`YOLOv5`增加DropBlock和GeneralizedAttention插件，其配置文件如下：
```suggestion
MMYOLO 支持在 BackBone 的不同 Stage 后增加如 `none_local`、`dropout` 等插件，用户可以直接通过修改配置文件中 `backbone` 的 `plugins` 参数来实现对插件的管理。例如为 YOLOv5 增加 `DropBlock` 和 `GeneralizedAttention` 插件，其配置文件如下：
```

2022-09-28 00:41 UTC, PeterH0323 commented on docs/zh_cn/advanced_guides/how_to.md
> +`cfg`参数表示插件的具体配置，`stages`参数表示是否在backbone对应的stage后面增加插件，列表`stages`的长度需要和backbone的stage数量相同。
```suggestion
`cfg` 参数表示插件的具体配置，`stages` 参数表示是否在 backbone 对应的stage 后面增加插件，列表 `stages` 的长度需要和 `backbone` 的 `stage` 数量相同。
```

2022-09-28 00:41 UTC, PeterH0323 commented on docs/zh_cn/advanced_guides/how_to.md
> +如果你想堆叠多个Neck，可以直接在配置文件中的Neck参数，MMYOLO支持以`List`形式拼接多个Neck配置，你需要保证的是上一个Neck的输出通道与下一个Neck的输入通道相匹配。如需要调整通道，可以插入`mmdet.ChannelMapper`模块用来对齐多个Neck之间的通道数量。具体配置如下：
```suggestion
如果你想堆叠多个 Neck，可以直接在配置文件中的 Neck 参数，MMYOLO 支持以 `List` 形式拼接多个 Neck 配置，你需要保证的是上一个 Neck 的输出通道与下一个 Neck 的输入通道相匹配。如需要调整通道，可以插入 `mmdet.ChannelMapper` 模块用来对齐多个 Neck 之间的通道数量。具体配置如下：
```

2022-09-28 09:22 UTC, PeterH0323 requested changes

2022-09-28 09:22 UTC, PeterH0323 commented on docs/zh_cn/advanced_guides/how_to.md
> +MMYOLO支持在BackBone的不同Stage后增加如none_local、dropout等插件，用户可以直接通过修改config中backbone的plugins参数来实现对插件的管理。例如为`YOLOv5`增加DropBlock和GeneralizedAttention插件，其配置文件如下：
```suggestion
MMYOLO 支持在 BackBone 的不同 Stage 后增加如 `none_local`、`dropout` 等插件，用户可以直接通过修改 config 文件中 `backbone` 的 `plugins 参数来实现对插件的管理。例如为 `YOLOv5` 增加 `DropBlock` 和 `GeneralizedAttention` 插件，其配置文件如下：
```

2022-09-28 09:22 UTC, PeterH0323 commented on docs/zh_cn/advanced_guides/how_to.md
> +`cfg`参数表示插件的具体配置，`stages`参数表示是否在backbone对应的stage后面增加插件，长度需要和backbone的stage数量相同。
```suggestion
`cfg` 参数表示插件的具体配置，`stages` 参数表示是否在 backbone 对应的 stage 后面增加插件，长度需要和 backbone 的 stage 数量相同。
```

2022-09-29 05:16 UTC, hhaAndroid commented on docs/zh_cn/advanced_guides/how_to.md
> +MMYOLO 支持在 BackBone 的不同 Stage 后增加如 `none_local`、`dropout` 等插件，用户可以直接通过修改 config 文件中 `backbone` 的 `plugins` 参数来实现对插件的管理。例如为 `YOLOv5` 增加 `DropBlock` 和 `GeneralizedAttention` 插件，其配置文件如下：
dropout -> dropblock

2022-09-29 05:16 UTC, hhaAndroid commented on docs/zh_cn/advanced_guides/how_to.md
> +                cfg=dict(
没看到 dropblock

2022-09-29 05:16 UTC, hhaAndroid commented on docs/zh_cn/advanced_guides/how_to.md
> +## 应用多个Neck
```suggestion
## 应用多个 Neck
```

2022-09-29 05:16 UTC, hhaAndroid commented on docs/zh_cn/advanced_guides/how_to.md
> +如果你想堆叠多个 Neck，可以直接在配置文件中的 Neck 参数，MMYOLO支持以 `List` 形式拼接多个 Neck 配置，你需要保证的是上一个 Neck 的输出通道与下一个 Neck 的输入通道相匹配。如需要调整通道，可以插入 `mmdet.ChannelMapper` 模块用来对齐多个 Neck 之间的通道数量。具体配置如下：
MMYOLO 支持以

2022-09-29 05:16 UTC, hhaAndroid commented on mmyolo/models/backbones/base_backbone.py
> +        in_channels = make_divisible(setting[1], self.widen_factor)
This is not reasonable to write, yolox can make mistakes

2022-09-29 07:36 UTC, hhaAndroid approved these changes

2022-09-29 07:36 UTC, merged