update deploy docs
open-mmlab/mmyolo pull request #785
Opened 2023-05-22 06:17 UTC by huayuan4396

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation for this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit tests to ensure the correctness.
3. If the modification has a potential influence on downstream projects, this PR should be tested with downstream projects, like MMDetection or MMClassification.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2023-05-22 06:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/open-mmlab/mmyolo?pullRequest=785) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmyolo?pullRequest=785) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmyolo?pullRequest=785) it.</sub>

2023-05-23 02:28 UTC, RunningLeon commented
@huayuan4396 may fix ci errors

2023-05-23 02:46 UTC, RunningLeon commented on docs/en/recommended_topics/deploy/mmdeploy_guide.md
> +
here should be formatted as 
:::{note}
If you install mmdeploy prebuilt package, please also clone its repository with below command to get the deployment configs and tools.

```bash
git clone https://github.com/open-mmlab/mmdeploy.git --depth=1
```

:::

2023-05-23 03:13 UTC, RunningLeon commented on docs/en/recommended_topics/deploy/mmdeploy_guide.md
> +Suppose the working directory is the root path of mmyolo. Take [YoloV5](https://github.com/open-mmlab/mmyolo/blob/main/configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py) model as an example. You
downloading config and ckpt should use `mim download mmyolo --config xx --dest ./workdir`

2023-05-23 03:14 UTC, RunningLeon commented on docs/en/recommended_topics/deploy/mmdeploy_guide.md
> +#
should be removed ?

2023-05-23 03:15 UTC, RunningLeon commented on docs/en/recommended_topics/deploy/mmdeploy_guide.md
> +#### MMDeploy Installed with pip install
Usage with MMDeploy API

2023-05-23 09:11 UTC, RunningLeon commented on docs/zh_cn/recommended_topics/deploy/mmdeploy_guide.md
> +更多介绍和使用指南见 https://github.com/open-mmlab/mmdeploy/blob/main/docs/zh_cn/get_started.md
may use the readthedocs link https://mmdeploy.readthedocs.io/zh_CN/latest/get_started.html

2023-05-23 09:12 UTC, RunningLeon commented on docs/zh_cn/recommended_topics/deploy/mmdeploy_guide.md
> +```{note}
this note should be formated as comment before.

2023-05-23 09:14 UTC, RunningLeon commented on docs/zh_cn/recommended_topics/deploy/mmdeploy_guide.md
> +- `--metrics`: 用于评估 MMYOLO 中定义的模型的指标，如 COCO 标注格式的 "proposal"。
does not have this argument. Pls. check the rest arguments 
https://github.com/open-mmlab/mmdeploy/blob/e47c6400b0f8bc1018bcc138b10c6d12bd5ceb26/tools/test.py#L14

2023-05-23 10:01 UTC, RunningLeon commented on docs/en/recommended_topics/deploy/mmdeploy_guide.md
> +
@huayuan4396 it seems this could work as well. may keep as original

2023-05-31 08:06 UTC, RunningLeon commented on docs/en/recommended_topics/deploy/mmdeploy_guide.md
> +If you install mmdeploy prebuilt package, please also clone its repository by 'git clone https://github.com/open-mmlab/mmdeploy.git --depth=1' to get the deployment config files.
actually, mmyolo has its own deploy configs. So to clone mmdeploy is to get tools.

2023-05-31 08:12 UTC, RunningLeon commented on docs/en/recommended_topics/deploy/mmdeploy_guide.md
> +If you install mmdeploy prebuilt package, please also clone its repository by 'git clone https://github.com/open-mmlab/mmdeploy.git --depth=1' to get the deployment config files.
fix typo and remove `\` in line 98 
```
\`YOLOv5\` to \`ONNXRuntim\`
```

2023-05-31 08:13 UTC, RunningLeon commented on docs/en/recommended_topics/deploy/mmdeploy_guide.md
> +If you install mmdeploy prebuilt package, please also clone its repository by 'git clone https://github.com/open-mmlab/mmdeploy.git --depth=1' to get the deployment config files.
fix typo in line 56 `nums` -> `nms`

2023-05-31 08:20 UTC, RunningLeon commented on docs/en/recommended_topics/deploy/mmdeploy_guide.md
> +
`‘tensorrt’` -> `'tensorrt'` in line 139

2023-05-31 08:26 UTC, RunningLeon commented on docs/en/recommended_topics/deploy/mmdeploy_guide.md
> +#### MMDeploy Installed from Source Code
Deploy with mmdeploy tools

2023-05-31 08:26 UTC, RunningLeon commented on docs/en/recommended_topics/deploy/mmdeploy_guide.md
> +#### Usage with MMDeploy API
Deploy with mmdeploy API

2023-05-31 08:43 UTC, RunningLeon commented on docs/zh_cn/recommended_topics/deploy/mmdeploy_guide.md
> +```{note}
修改这里 需要配置文件和tools

2023-05-31 08:46 UTC, RunningLeon requested changes
@huayuan4396 pls. resolve comments

2023-06-01 01:56 UTC, RunningLeon commented
@hhaAndroid Hi, could you review this PR?

2023-06-09 09:52 UTC, RunningLeon approved these changes
LGTM

2023-06-12 02:03 UTC, hhaAndroid approved these changes

2023-06-12 02:05 UTC, merged