* format docs
open-mmlab/mmyolo pull request #83
Opened 2022-09-24 04:09 UTC by xin-li-67

## Motivation

refine the documents

## Modification

update docs

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDetection or MMClassification.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2022-09-24 04:10 UTC, PeterH0323 commented
Hi @xin-li-67 

Pls merge to `dev` branch.

2022-09-24 04:12 UTC, PeterH0323 requested changes

2022-09-24 04:12 UTC, PeterH0323 commented on docs/en/algorithm_descriptions/model_design.md
> +We reproduce the YOLO series Neck components in the similar way as the `BaseBackbone`, and we can mainly divide them into `Reduce layer` , `UpSample layer` , `TopDown layer` , `DownSample layer`, `Bo
```suggestion
We reproduce the YOLO series Neck components in the similar way as the `BaseBackbone`, and we can mainly divide them into `Reduce layer`, `UpSample layer`, `TopDown layer`, `DownSample layer`, `BottomUP layer` and `output convolution layer`. Each layer can be customized its internal construction by the inheritance and rewrite from the `build_xx` method.
```

2022-09-24 14:56 UTC, hhaAndroid commented
@xin-li-67 Please synchronize the dev branch

2022-09-25 00:01 UTC, xin-li-67 commented
> 

Synced with the dev branch! thanks for the update @hhaAndroid

2022-09-25 08:54 UTC, RangeKing requested changes

2022-09-25 08:54 UTC, RangeKing commented on docs/en/advanced_guides/data_flow.md
> +Mixed image data augmentation is similar to Mosaic and MixUp, in which the annotation information of multiple images needs to be obtained for fusion during the running process. In the OpenMMLab data
```suggestion
Mixed image data augmentation is similar to Mosaic and MixUp, in which the annotation information of multiple images needs to be obtained for fusion during the running process. In the OpenMMLab data augmentation pipeline, other indexes of the dataset are generally not available. In order to achieve the above function, in the YOLOX reproduced in MMDetection, the concept of [MultiImageMixDataset](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/datasets/dataset_wrappers.py#L338) dataset wrapper is proposed.
```

2022-09-25 08:54 UTC, RangeKing commented on docs/en/advanced_guides/data_flow.md
> +However, this implementation has a disadvantage: for users who are not familiar with MMDetection, they will forget that data augmentation methods like Mosaic must be used together with `MultiImageMix
```suggestion
However, this implementation has a disadvantage: users unfamiliar with MMDetection will forget those data augmentation methods like Mosaic must be used together with `MultiImageMixDataset`, increasing the usage complexity. Moreover, it is hard to understand as well.
```

2022-09-25 08:54 UTC, RangeKing commented on docs/en/advanced_guides/data_flow.md
> +To address this problem, further simplications are made in MMYOLO, which directly let `pipeline` get `dataset`. In this way the implementation of `Mosaic` and other data augmentation methods can be a
```suggestion
To address this problem, further simplifications are made in MMYOLO, which directly lets `pipeline` get `dataset`. In this way, the implementation of `Mosaic` and other data augmentation methods can be achieved and used just as the random flip, without a data wrapper anymore. The new configuration method is as follows:
```

2022-09-25 08:54 UTC, RangeKing commented on docs/en/user_guides/config.md
> +[Dataloaders](https://pytorch.org/docs/stable/data.html?highlight=data%20loader#torch.utils.data.DataLoader) are required for the training, validation, and testing of the [runner](https://mmengine.re
```suggestion
[Dataloaders](https://pytorch.org/docs/stable/data.html?highlight=data%20loader#torch.utils.data.DataLoader) are required for the training, validation, and testing of the [runner](https://mmengine.readthedocs.io/en/latest/tutorials/runner.html). Dataset and data pipeline need to be set to build the dataloader. Due to the complexity of this part, we use intermediate variables to simplify the writing of dataloader configs. More complex data augmentation methods are adopted for the lightweight object detection algorithms in MMYOLO. Therefore, MMYOLO has a wider range of dataset configurations than other models in MMDetection.
```

2022-09-25 08:54 UTC, RangeKing commented on docs/zh_cn/algorithm_descriptions/model_design.md
> +总的来说，在 MMYOLO 中只需要做到将 `model` + `loss_by_feat` 部分解耦，用户就可以通过修改配置实现任意模型配合任意 `loss_by_feat` 的计算过程。例如将 YOLOv5 模型应用 YOLOX 的 `loss_by_feat` 等。
```suggestion
总的来说，在 MMYOLO 中只需要做到将 `model` + `loss_by_feat` 部分解耦，用户就可以通过修改配置实现任意模型配合任意的 `loss_by_feat` 计算过程。例如将 YOLOv5 模型应用 YOLOX 的 `loss_by_feat` 等。
```

2022-09-25 08:57 UTC, RangeKing commented
Hi @xin-li-67, thanks for your contribution.
Please check the requested changes.

2022-09-25 13:50 UTC, hhaAndroid approved these changes

2022-09-25 13:51 UTC, merged