[Feature] Support RTMDet
open-mmlab/mmyolo pull request #85
Opened 2022-09-25 02:48 UTC by hhaAndroid

Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Please describe the motivation of this PR and the goal you want to achieve through this PR.

## Modification

Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDetection or MMClassification.
4. The documentation has been modified accordingly, like docstring or example tutorials.

2022-09-25 03:08 UTC, PeterH0323 requested changes

2022-09-25 03:08 UTC, PeterH0323 commented on mmyolo/models/dense_heads/rtmdet_head.py
> +    """YOLOXHead head used in `YOLOX <https://arxiv.org/abs/2107.08430>`_.
Should be change to RTMDet paper ?

2022-09-25 03:08 UTC, PeterH0323 commented on mmyolo/models/necks/cspnext_pafpn.py
> +    ) -> None:
```suggestion
    ):
```

2022-09-25 03:08 UTC, PeterH0323 commented on mmyolo/models/dense_heads/rtmdet_head.py
> +                    unmap_outputs=True):
```suggestion
                    unmap_outputs=True) -> Union[None, list]:
```

2022-09-25 03:08 UTC, PeterH0323 commented on mmyolo/models/dense_heads/rtmdet_head.py
> +                     batch_gt_instances_ignore: OptInstanceList = None):
```suggestion
                     batch_gt_instances_ignore: OptInstanceList = None) -> dict:
```

2022-09-25 03:08 UTC, PeterH0323 commented on mmyolo/models/dense_heads/rtmdet_head.py
> +                            stride: List[int]):
Should add return type hint.

2022-09-25 03:08 UTC, PeterH0323 commented on mmyolo/models/dense_heads/rtmdet_head.py
> +                            unmap_outputs=True):
```suggestion
                            unmap_outputs=True) -> list:
```

2022-09-25 03:20 UTC, RangeKing commented on mmyolo/models/necks/cspnext_pafpn.py
> +        if idx == 2:
```suggestion
        if idx in (1, 2):
```
According to https://github.com/open-mmlab/mmdetection/blob/a3cf5368fd3725c9848479f54675eb70bb0fa00b/mmdet/models/necks/cspnext_pafpn.py#L70-L78

2022-09-25 03:20 UTC, RangeKing commented on mmyolo/models/necks/cspnext_pafpn.py
> +                    act_cfg=self.act_cfg))
```suggestion
        return CSPLayer(
            self.in_channels[idx - 1] * 2,
            self.in_channels[idx - 1],
            num_blocks=self.num_csp_blocks,
            add_identity=False,
            use_cspnext_block=True,
            expand_ratio=self.expand_ratio,
            conv_cfg=self.conv_cfg,
            norm_cfg=self.norm_cfg,
            act_cfg=self.act_cfg)
```

2022-09-27 08:19 UTC, Nioolek commented on configs/rtmdet/cspnext_imagenet_pretrain/README.md
> +## How to Train
Whether the `mim` command can be added

2022-09-27 08:22 UTC, hhaAndroid commented on configs/rtmdet/cspnext_imagenet_pretrain/README.md
> +## How to Train
No need to use mim, it's easier

2022-09-29 08:34 UTC, merged